#!/bin/bash
echo "Scrape Begin!"
echo "Start scraping Phon1!"
python scrap_v0.2_offerup_10_models.py --item 0
echo "End scraping Phon1!"
echo "Start scraping Phon2!"
python scrap_v0.2_offerup_10_models.py --item 1
echo "End scraping Phon2!"
echo "Start scraping Phon3!"
python scrap_v0.2_offerup_10_models.py --item 2
echo "End scraping Phon3!"
echo "Start scraping Phon4!"
python scrap_v0.2_offerup_10_models.py --item 3
echo "End scraping Phon4!"
echo "Start scraping Phon5!"
python scrap_v0.2_offerup_10_models.py --item 4
echo "End scraping Phon5!"
echo "Start scraping Phon6!"
python scrap_v0.2_offerup_10_models.py --item 5
echo "End scraping Phon6!"
echo "Start scraping Phon7!"
python scrap_v0.2_offerup_10_models.py --item 6
echo "End scraping Phon7!"
echo "Start scraping Phon8!"
python scrap_v0.2_offerup_10_models.py --item 7
echo "End scraping Phon8!"
echo "Start scraping Phon9!"
python scrap_v0.2_offerup_10_models.py --item 8
echo "End scraping Phon9!"
echo "Start scraping Phon10!"
python scrap_v0.2_offerup_10_models.py --item 9
echo "End scraping Phon10!"
