#!/bin/bash
echo "Scrape Begin!"
echo "Start scraping IPhoneX!"
python scrap_v0.2_offerup_10_models.py --item 0
echo "End scraping IPhoneX!"
echo "Start scraping IPhone7!"
python scrap_v0.2_offerup_10_models.py --item 1
echo "End scraping IPhone7!"
echo "Start scraping IPhone6s!"
python scrap_v0.2_offerup_10_models.py --item 2
echo "End scraping IPhone6s!"
echo "Start scraping IPhone6!"
python scrap_v0.2_offerup_10_models.py --item 3
echo "End scraping IPhone6!"
echo "Start scraping SamsungGalaxyS9!"
python scrap_v0.2_offerup_10_models.py --item 4
echo "End scraping SamsungGalaxyS9!"
echo "Start scraping SamsungGalaxyS8!"
python scrap_v0.2_offerup_10_models.py --item 5
echo "End scraping SamsungGalaxyS8!"
echo "Start scraping SamsungGalaxyS7!"
python scrap_v0.2_offerup_10_models.py --item 6
echo "End scraping SamsungGalaxyS7!"
echo "Start scraping Pixel4!"
python scrap_v0.2_offerup_10_models.py --item 7
echo "End scraping Pixel4!"
echo "Start scraping Pixel3!"
python scrap_v0.2_offerup_10_models.py --item 8
echo "End scraping Pixel3!"
echo "Start scraping Pixel2!"
python scrap_v0.2_offerup_10_models.py --item 9
echo "End scraping Pixel2!"
