echo "Start scraping Phon7!"
python scrap_v0.2_offerup_10_models.py --item 6
echo "End scraping Phon7!"
echo "Start scraping Phon8!"
python scrap_v0.2_offerup_10_models.py --item 7
echo "End scraping Phon8!"
echo "Start scraping Phon9!"
python scrap_v0.2_offerup_10_models.py --item 8
echo "End scraping Phon9!"
echo "Start scraping Phon10!"
python scrap_v0.2_offerup_10_models.py --item 9
echo "End scraping Phon10!"
